version: "3"
services: 
  dndserver:
    build: WebServer
    ports: 
      - "1337:1337"
      - "8080:8080"
    volumes: 
      - ./WebServer:/usr/src/app
      - /usr/src/app/node_modules
  dndangular:
    build: DnD
    ports:
      - "4200:4200"
    volumes: 
      - ./DnD:/usr/src/app
      - /usr/src/app/node_modules